/**
 * Base Remotion Template for Sandpack
 *
 * This module exports all files needed to run a Remotion project
 * inside the Sandpack virtual browser environment.
 *
 * File Structure in Sandpack:
 * /
 * ├── App.tsx          # Main entry with Remotion Player
 * ├── src/
 * │   ├── Composition.tsx  # Video composition component
 * │   ├── Root.tsx         # Remotion root with Composition registration
 * │   ├── index.ts         # Remotion entry point
 * │   └── index.css        # Global styles
 * └── (auto-generated by Sandpack)
 *     ├── index.tsx
 *     └── public/index.html
 */

import { appFile } from "./files/app";
import { compositionFile } from "./files/composition";
import { rootFile } from "./files/root";
import { indexEntryFile } from "./files/index-entry";
import { stylesFile } from "./files/styles";

// Type for Sandpack files object
export type SandpackFiles = Record<string, string>;

/**
 * Complete Sandpack files configuration for base Remotion template
 */
export const baseRemotionFiles: SandpackFiles = {
  // Main App entry point (what Sandpack renders)
  "/App.tsx": appFile,

  // Remotion source files (organized in /src folder)
  "/src/Composition.tsx": compositionFile,
  "/src/Root.tsx": rootFile,
  "/src/index.ts": indexEntryFile,
  "/src/index.css": stylesFile,
};

/**
 * Sandpack custom setup for Remotion projects
 */
export const baseRemotionDependencies = {
  remotion: "4.0.100",
  "@remotion/player": "4.0.100",
  react: "18.2.0",
  "react-dom": "18.2.0",
};

/**
 * Default active file when opening the editor
 */
export const defaultActiveFile = "/src/Composition.tsx";
